/*
 * Project Euler 44
 * "Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?"
 */
object euler44 {
  def main(args: Array[String]): Unit = {

    def isPent(x: Long): Boolean = {
      val test: Double = (scala.math.sqrt((24.0 * x.toDouble) + 1.0) + 1.0) / 6.0
      if (test % 1 == 0.0) true
      else false
    }

    def pentagon(x: Long): Long = {
      val answer = x * (3 * x - 1) / 2
      answer
    }

    def createPent(start: Long, stop: Long, runningList: List[Long] = List()): List[Long] = {
      val pent = pentagon(start)
      val pentList = pent :: runningList
      if (start == stop) return pentList
      else createPent(start + 1, stop, pentList)
    }

    def recur(x: Long, running: List[Long] = List()): Long = {
      val xp = pentagon(x)
      val pentList = xp :: running
      def util(index: Int): Long = {
        val i = pentList(index)
        if (i <= 0) recur(x + 1, pentList)
        else if (isPent(xp - i) && isPent(xp + i)) xp - i
        else util(index + 1)
      }
      util(0)
    }

    println("Answer: " + Math.abs(recur(0)))
  }
}
