/**
 * Project Euler 
 * Problem 29
 * "How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"
 * October 7, 2017
 */
val powers = for(i <- 2 to 100; n <- 2 to 100) yield { Math.pow(i, n) }
val answer = powers.distinct.length